version: 2

jobs:
  publish:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
      - run: make
      - run: make tag
      - run: make publish

workflows:
  version: 2
  merge:
    jobs:
      - publish:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - publish
